### PR TITLE
Fixes: #316

### PR DESCRIPTION
**Pull request by pasevin**
I've added a new dependency to ```js-base64``` which allows to use Base64 encoding both on client and server without issues.

### CODE REVIEW

**Comment by k3nsei** [comment]
Please try to use https://angular.io/api/common/isPlatformServer and https://nodejs.org/docs/latest-v10.x/api/buffer.html#buffer_class_method_buffer_from_string_encoding to not introduce additional dependencies.

So in `projects/ng-in-viewport/src/lib/in-viewport-config.ts`
You can try to do something like
```ts
private static readonly ngInjector: Injector = Injector.create({providers: []});

private static toBase64(input: string): string {
  if(typeof input !== 'string') {
    throw new TypeError(`input isn't a string`);
  }

  return isPlatformServer(ngInjector.get(PLATFORM_ID))
    ? Buffer.from(input).toString('base64')
    :  window.btoa(input);
}

private static hash(input: object): string {
    return InViewportConfig.toBase64(InViewportConfig.stringify(input));
}
```

**Comment by k3nsei** [comment]
@pasevin please add `code` to your entry in `.all-contributorsrc`

and then run
```
yarn run all-contributors generate
```

**Comment by pasevin** [comment]
Yeah, that was my initial idea to use ```isPlatformServer```, but went with a lazy way :) Do you want me to update this pull request?

**Comment by k3nsei** [comment]
Yes, I'm currently at work. So it would be helpful.

**Comment by pasevin** [comment]
Sorry, I tried, but gettings ```NullInjectorError: No provider for InjectionToken Platform ID!``` and can't find a way to avoid it...
I'm not familiar with this issue.

**Comment by pasevin** [comment]
And I had to address this issue as well: https://stackoverflow.com/a/54025062/1617590

**Comment by k3nsei** [comment]
No problem please commit you code, and I will pick it up from there.

**Comment by k3nsei** [comment]
@pasevin please look at https://github.com/k3nsei/ng-in-viewport/pull/319 and verify if it will solve an issue

**Pull request closed without merging**
